language: node_js
node_js: lts/*
script:
    - yarn build
    - yarn lint
    - yarn docs
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    github_url: github.schibsted.io
    local_dir: ./site
    email: travis@schibsted.com
    name: Travis CI
    on:
        branch: master
group: container
