name: Deploy to GitHub Pages

on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: |
                  yarn
            - name: Build Packages
              run: |
                  yarn build
