name: Deploy to GitHub Pages

on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm install
            - name: Build Packages
              run: npm run build
